### ISSUE TITLE
FIFO Support

### ISSUE THREAD

**Issue by jtrunick** [awslabs/amazon-sqs-java-extended-client-lib#16]
I changed our existing queue to wrapper it with this extended support.  We are seeing this now:
The input receipt handle is invalid. (Service: AmazonSQS; Status Code: 404; Error Code: ReceiptHandleIsInvalid; Request ID: ba9421e9-a9d2-56ba-8e17-70ff7190f05a)

This is on consuming the queue, we are able to put a message on the queue, and the body is being stored on the S3 bucket.

**Comment by kuba-aws** [comment]
Please use the 1.0.1 release which has been tested with SQS FIFO queues.
