### ISSUE TITLE
Python version of this Library

### ISSUE THREAD

**Issue by timothymugayi** [awslabs/amazon-sqs-java-extended-client-lib#19]
Hi Guys

Is there a python version of this library? I seem to only see dot net and java.

**Comment by asalem** [comment]
Only Java support is available

**Comment by gaurav-** [comment]
That's strange. Why not release the same functionality for other SDKs? 🤔

**Comment by monk8800** [comment]
For those wishing to have the python version please reachout to me, ended up building a wrapper around boto3 with the same logic as in the java version 

```

		if self.always_through_s3 or self.__is_large(str(message), message_attributes):
			if not self.s3_bucket_name.strip():
				raise ValueError('S3 bucket name cannot be null')
			message = str(self.__store_message_in_s3(message))
			message_attributes[SQSExtendedClientConstants.RESERVED_ATTRIBUTE_NAME.value] = {'StringValue': str(self.__get_string_size_in_bytes(message)), 'DataType': 'Number'}
			return self.sqs.send_message(QueueUrl=queue_url, MessageBody=message, MessageAttributes=message_attributes)
		else:
			return self.sqs.send_message(QueueUrl=queue_url, MessageBody=message)
```

**Comment by timothymugayi** [comment]
For those wishing to have the python version please reachout to me, ended up building a wrapper around boto3 with the same logic as in the java version 

```

		if self.always_through_s3 or self.__is_large(str(message), message_attributes):
			if not self.s3_bucket_name.strip():
				raise ValueError('S3 bucket name cannot be null')
			s3_key_message = str(self.__store_message_in_s3(message))
			message_attributes[SQSExtendedClientConstants.RESERVED_ATTRIBUTE_NAME.value] = {'StringValue': str(self.__get_string_size_in_bytes(message)), 'DataType': 'Number'}
			return self.sqs.send_message(QueueUrl=queue_url, MessageBody=s3_key_message, MessageAttributes=message_attributes)
		else:
			return self.sqs.send_message(QueueUrl=queue_url, MessageBody=message)
```

**Comment by timothymugayi** [comment]
@razeetg You may refer to my git repo. [https://github.com/timothymugayi/boto3-sqs-extended-client-lib](https://github.com/timothymugayi/boto3-sqs-extended-client-lib) Take note this is still a work in progress test cases code coverage etc TBD 

Using python > 3.x

```
$ virtualenv venv
$ source venv/Scripts/activate
$ pip install -r requirements.txt 
$ python test.py
```

**Comment by razeetg** [comment]
Thank you @timothymugayi , this looks wonderful!

**Comment by timothymugayi** [comment]
I would imagine i will have to address all the issues that have been logged in the java version, Some of the 12 issues in the list are valid

**Comment by loretoparisi** [comment]
@timothymugayi thanks a lot! Is this version an unofficial implementation?

**Comment by timothymugayi** [comment]
Yes, it's unofficial, if anyone wants to contribute they are free to do so.

**Comment by ziyanli-amazon** [comment]
It is live https://github.com/awslabs/amazon-sqs-python-extended-client-lib
