### ISSUE TITLE
SNS equivalent?

### ISSUE THREAD

**Issue by sql4bucks** [awslabs/amazon-sqs-java-extended-client-lib#20]
Is there an equivalent library that would handle large messages to SNS in the same way? Any plans?

**Comment by JacobJohansen** [comment]
@sql4bucks for extended sns https://github.com/VirginPulsePublic/amazon-sns-java-extended-client-lib

**Comment by james-bowen-au** [comment]
I'll second this. It would be useful to have something like this to send large payloads to a topic - a lot of our use cases for extended SQS revolve around a queue being one of many subscribers to a topic.

**Comment by adam-aws** [comment]
Hi, SNS team recently released the Amazon SNS Extended Client Library for Java https://github.com/awslabs/amazon-sns-java-extended-client-lib which handles messages that are greater than the current SNS limit of 256 KB, up to a maximum of 2 GB.

Will close this issue.
