### ISSUE TITLE
Allow Custom Message Size Threshold/Include Message Attributes' size in threshold

### ISSUE THREAD

**Issue by ss37** [awslabs/amazon-sqs-java-extended-client-lib#28]
Currently, DEFAULT_MESSAGE_SIZE_THRESHOLD = 256KB. This doesn't help if SQS messages have MessageAttributes that are not included in the size computed for the message.

One of the following would help:
1. Have a method that allows custom message size threshold in ExtendedClientConfiguration class
2. (or) While computing message size, include message attributes along with message content to calculate the actualy size of SQS message. 

Reference: "All parts of the message attribute, including name, type, and value, are included in the message size restriction, which is currently 256 KB (262,144 bytes)." [https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-attributes.html](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-attributes.html)

**Comment by adam-aws** [comment]
The message size threshold can be updated in ExtendedClientConfiguration class using withMessageSizeThreshold() since version 1.0.0
