### ISSUE TITLE
AmazonSQSExtendedClient does not have an implementation

### ISSUE THREAD

**Issue by mec2005** [awslabs/amazon-sqs-java-extended-client-lib#61]
Hi.
First of all I want to thank you for this solution.
I have an implementation that works fine, but when I updated AWSSDK.Core, AWSSDK.S3, AWSSDK.SimpleNotificationService and AWSSDK.SQS the client stopped working.

Now I have got the error.
```C#
System.TypeLoadException: 'Method 'get_Paginators' in type 'Amazon.SQS.ExtendedClient.AmazonSQSExtendedClient' from assembly 'Amazon.SQS.ExtendedClient, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'
```
``` C#
try            
{
    _queueUrl = config.Url;
    _s3Client = new AmazonS3Client(new BasicAWSCredentials(config.AccessKey, config.SecretKey), Amazon.RegionEndpoint.GetBySystemName(config.Region));
    _sqsClient = new AmazonSQSClient(config.AccessKey, config.SecretKey, Amazon.RegionEndpoint.GetBySystemName(config.Region));
    _extendedClient = new AmazonSQSExtendedClient(_sqsClient, new ExtendedClientConfiguration().WithLargePayloadSupportEnabled(_s3Client, config.BucketName));
    }
    catch (Exception ex)
    {
        _logger.LogError(ex, "Constructor: SqsService");
        throw;
    }
}
```
I'll thank you again if help me!

**Comment by adam-aws** [comment]
Hi @mec2005 , can you share the previous and new versions that you updated to and I'll be happy to take a look.

**Comment by mec2005** [comment]
For sure!
![image](https://user-images.githubusercontent.com/2211448/98415609-5c25e700-205c-11eb-831a-8a2dd6b3e16b.png)

**Comment by adam-aws** [comment]
Hi @mec2005 , looks like you are using the .Net version https://github.com/raol/amazon-sqs-net-extended-client-lib which isn't maintained by us. I saw you opened an issue with them.

Will close this issue since this should be handled by the maintainers of .Net version

**Comment by mec2005** [comment]
Thank you! I so sorry.
