### ISSUE TITLE
Consuming SQSEvent from lambda

### ISSUE THREAD

**Issue by gyoga99** [awslabs/amazon-sqs-java-extended-client-lib#62]
When consuming large payload event from SQS in aws lambda, should we build logic to get the payload from S3 and process?

**Comment by adam-aws** [comment]
You can have a look at this issue #31 and the following docs https://awslabs.github.io/aws-lambda-powertools-java/utilities/sqs_large_message_handling/ which might be able to address your use case.

**Comment by gyoga99** [comment]
Thanks Adam!

I tried to follow instructions there and ran into this issue 
https://github.com/awslabs/aws-lambda-powertools-java/issues/320

**Comment by adam-aws** [comment]
Looks like they have a fix on their end for that issue.

Will close this one, please reopen if needed.

**Comment by gyoga99** [comment]
Thank you!
