### ISSUE TITLE
Using the library with lambda  as event source mapping

### ISSUE THREAD

**Issue by mabdelazim** [awslabs/amazon-sqs-java-extended-client-lib#71]
We want to use the library in lambda handler which reads from SQS via event source mapping.
The issue is, SQS sends to the lambda SQSEvent which already includes the messages body.
We need to have a public API to extract the actually payload and takes SQSEvent as input instead of ReceiveMessageRequest.

**Comment by msailes** [comment]
Hi @mabdelazim ,

The Lambda Powertools for Java project handles this problem. 

https://awslabs.github.io/aws-lambda-powertools-java/utilities/sqs_large_message_handling/

Mark

**Comment by mabdelazim** [comment]
Thanks Mark.
Closing the issue.
