### ISSUE TITLE
How to identify file from S3 with message in the queue.

### ISSUE THREAD

**Issue by onsah** [awslabs/amazon-sqs-java-extended-client-lib#72]
Hi, I am planning to use this library but I can't find any documentation on how we can find the related file in the bucket. 

My use case is if some message fails to be processed or drops to the dead letter queue I would like to see and look through the contents of the file manually. Is it possible to achieve this with this library?

**Comment by adam-aws** [comment]
For a fallback mechanism you would need to implement it on your side.
So, if you're unable to retrieve the stored message that is in S3 using this library for whatever reason (or if you just want to look at the message), you'd have to implement the logic to access the S3 bucket where the message is stored. You can also just view the messages in the S3 UI console by going to the proper bucket.

**Comment by onsah** [comment]
@adam-aws I was asking about manual inspecting, so if the message processor is failed can I identify the s3 file of the related message manually?

I inspected the message content in SQS and I found it is easy to figure out which file is linked to the message. So I am closing this.
