### ISSUE TITLE
Invalid ReceiptHandle on ChangeMessageVisibilityRequest

### ISSUE THREAD

**Issue by glidester** [awslabs/amazon-sqs-java-extended-client-lib#9]
Just noticed that I can't successfully call 'changeMessageVisibility' on the AmazonSQSExtendedClient class.

This is because the 'AmazonSQSExtendedClient' does not override the 'changeMessageVisibility' method of the 'AmazonSQSExtendedClientBase' and work it's magic on the ReceiptHandle to strip the "-..s3Key..-" prefix (which does happen for the 'deleteMessage' method).

**Comment by glidester** [comment]
Just found that @cfinerty has already fixed this in a pull request:
https://github.com/awslabs/amazon-sqs-java-extended-client-lib/pull/4

Would be good to get it merged soon please :)

Thanks

**Comment by aws-aminsuzani** [comment]
Hello, thanks for the information. We have added an item to our backlog to test, merge and accept the referenced pull request. We will provide an update once the merge is completed.

**Comment by kuba-aws** [comment]
Version 1.0.1 addresses this issue.
